Devop: dded fix for continue button
MyEtherWallet/mew-ccswap pull request #5
Opened 2022-06-02 21:30 UTC by jmjles

2022-06-02 22:58 UTC, andrewdahn approved these changes

2022-06-03 19:25 UTC, gamalielhere requested changes

2022-06-03 19:25 UTC, gamalielhere commented on src/components/BuyForm/BuyForm.vue
> +    ? true
don't have to do this since the statement already resolves to true or false.

2022-06-07 18:24 UTC, gamalielhere approved these changes

2022-06-07 19:04 UTC, merged